name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app

    # 🔥 NEW PART (CD)
    - name: Stop old container
      run: |
        docker stop fastapi-container || true
        docker rm fastapi-container || true

    - name: Pull latest image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app

    - name: Run new container
      run: |
        docker run -d \
        -p 8000:8000 \
        --name fastapi-container \
        -e API_KEY=${{ secrets.API_KEY }} \
        ${{ secrets.DOCKER_USERNAME }}/fastapi-app